name: image-processing-system

services:
  notification-service:
    build:
      context: .
      args:
        MODE: development
    environment:
      MODE: development
      BASE_URL: http://localhost:8002
      LOGS_ROOT: /var/log/notification_service/
      STATIC_ROOT: /var/www/notification_service/static/
      MEDIA_ROOT: /var/www/notification_service/media/
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8002:8002
