services:
  notification-service:
    container_name: notification_service
    restart: unless-stopped
    networks:
      - shared_network

volumes:
  database:

networks:
  shared_network:
    driver: bridge
